import type { Card } from "./types";

export const starterDeck: Card[] = [
  {
    id: "slash-1",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-1",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "wine-1",
    name: "酒",
    kind: "wine",
    cost: 0,
    value: 1,
    text: "下一張斬傷害 +1，並恢復 1 點體力。",
  },
  {
    id: "manual-1",
    name: "兵書",
    kind: "draw",
    cost: 1,
    value: 2,
    text: "抽 2 張牌。",
  },
  {
    id: "pierce-1",
    name: "破甲",
    kind: "pierce",
    cost: 1,
    value: 1,
    text: "造成 1 點傷害，移除敵人防守，下一次斬傷害 +1。",
  },
  {
    id: "slash-2",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-2",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-3",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "manual-2",
    name: "兵書",
    kind: "draw",
    cost: 1,
    value: 2,
    text: "抽 2 張牌。",
  },
  {
    id: "wine-2",
    name: "酒",
    kind: "wine",
    cost: 0,
    value: 1,
    text: "下一張斬傷害 +1，並恢復 1 點體力。",
  },
  {
    id: "pierce-2",
    name: "破甲",
    kind: "pierce",
    cost: 1,
    value: 1,
    text: "造成 1 點傷害，移除敵人防守，下一次斬傷害 +1。",
  },
  {
    id: "slash-4",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
];
