import type { Card } from "./types";

export const equipmentEffects = {
  greenDragonBlade: "每回合第一次斬額外 +1 傷害",
  diluHorse: "每場戰鬥第一次受到攻擊時自動閃避",
  taipingManual: "每回合第一次兵書額外抽 1 張",
} as const;

const cardVisuals: Record<string, Pick<Card, "illustration" | "visualPrompt">> = {
  斬: {
    illustration: "card-slash",
    visualPrompt: "刀光破空，古代戰場攻擊卡牌插圖，紅色能量，三國卡牌風",
  },
  閃: {
    illustration: "card-dodge",
    visualPrompt: "武將側身閃避箭矢與刀光，藍色速度殘影，三國防禦卡牌插圖",
  },
  酒: {
    illustration: "card-wine",
    visualPrompt: "古代酒壺與熱烈戰意，暖色光芒恢復體力，三國卡牌插圖",
  },
  兵書: {
    illustration: "card-manual",
    visualPrompt: "竹簡兵書攤開，墨色策略紋路與燭光，三國策略卡牌插圖",
  },
  破甲: {
    illustration: "card-pierce",
    visualPrompt: "鋒刃擊碎甲片，橘色衝擊光，古代戰場破防卡牌插圖",
  },
  青龍偃月刀: {
    illustration: "card-green-dragon-blade",
    visualPrompt: "青龍偃月刀泛起青金龍影，關羽武器裝備卡，東方史詩卡牌插圖",
  },
  的盧馬: {
    illustration: "card-dilu-horse",
    visualPrompt: "白色的盧馬踏煙奔馳，戰場閃避與守護意象，三國裝備卡牌插圖",
  },
  太平要術: {
    illustration: "card-taiping-manual",
    visualPrompt: "古老道術卷軸，符籙與金色術法光芒，三國策略裝備卡牌插圖",
  },
  連斬: {
    illustration: "card-combo-slash",
    visualPrompt: "連續刀光追擊敵陣，深紅速度線與破勢感，三國攻擊卡牌插圖",
  },
  固守: {
    illustration: "card-guard",
    visualPrompt: "盾陣穩住陣腳，青藍防護光幕，古代戰場防禦卡牌插圖",
  },
  激勵: {
    illustration: "card-rally",
    visualPrompt: "戰旗高舉鼓舞士氣，綠金光芒恢復與補牌意象，三國策略卡牌插圖",
  },
  火攻: {
    illustration: "card-fire-attack",
    visualPrompt: "火焰席捲敵陣，橘紅烈焰打斷蓄力，三國火攻策略卡牌插圖",
  },
};

const baseStarterDeck: Omit<Card, "illustration" | "visualPrompt">[] = [
  {
    id: "slash-1",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-1",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "wine-1",
    name: "酒",
    kind: "wine",
    cost: 0,
    value: 1,
    text: "下一張斬傷害 +1，並恢復 1 點體力。",
  },
  {
    id: "manual-1",
    name: "兵書",
    kind: "draw",
    cost: 1,
    value: 2,
    text: "抽 2 張牌。",
  },
  {
    id: "pierce-1",
    name: "破甲",
    kind: "pierce",
    cost: 1,
    value: 1,
    text: "造成 1 點傷害，移除敵人防守，下一次斬傷害 +1。",
  },
  {
    id: "slash-2",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-2",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-3",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "manual-2",
    name: "兵書",
    kind: "draw",
    cost: 1,
    value: 2,
    text: "抽 2 張牌。",
  },
  {
    id: "wine-2",
    name: "酒",
    kind: "wine",
    cost: 0,
    value: 1,
    text: "下一張斬傷害 +1，並恢復 1 點體力。",
  },
  {
    id: "pierce-2",
    name: "破甲",
    kind: "pierce",
    cost: 1,
    value: 1,
    text: "造成 1 點傷害，移除敵人防守，下一次斬傷害 +1。",
  },
  {
    id: "slash-4",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-3",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-5",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "wine-3",
    name: "酒",
    kind: "wine",
    cost: 0,
    value: 1,
    text: "下一張斬傷害 +1，並恢復 1 點體力。",
  },
  {
    id: "dodge-4",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-6",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-5",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-7",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "slash-8",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "green-dragon-blade-1",
    name: "青龍偃月刀",
    kind: "equipment",
    cost: 1,
    value: 0,
    text: `裝備。攻擊流。${equipmentEffects.greenDragonBlade}。`,
  },
  {
    id: "dilu-horse-1",
    name: "的盧馬",
    kind: "equipment",
    cost: 1,
    value: 0,
    text: `裝備。防守流。${equipmentEffects.diluHorse}。`,
  },
  {
    id: "taiping-manual-1",
    name: "太平要術",
    kind: "equipment",
    cost: 1,
    value: 0,
    text: `裝備。策略流。${equipmentEffects.taipingManual}。`,
  },
  {
    id: "combo-slash-1",
    name: "連斬",
    kind: "combo",
    cost: 1,
    value: 1,
    text: "趁敵勢已亂，連續追擊。造成 1 點傷害；若敵人已受傷，抽 1 張牌。",
  },
  {
    id: "combo-slash-2",
    name: "連斬",
    kind: "combo",
    cost: 1,
    value: 1,
    text: "趁敵勢已亂，連續追擊。造成 1 點傷害；若敵人已受傷，抽 1 張牌。",
  },
  {
    id: "guard-1",
    name: "固守",
    kind: "guard",
    cost: 1,
    value: 1,
    text: "穩住陣腳，減少下一次傷害。本回合下一次受到傷害 -1。",
  },
  {
    id: "guard-2",
    name: "固守",
    kind: "guard",
    cost: 1,
    value: 1,
    text: "穩住陣腳，減少下一次傷害。本回合下一次受到傷害 -1。",
  },
  {
    id: "rally-1",
    name: "激勵",
    kind: "rally",
    cost: 1,
    value: 1,
    text: "重整士氣，恢復體力並補充手牌。抽 1 張牌並回復 1 點體力。",
  },
  {
    id: "rally-2",
    name: "激勵",
    kind: "rally",
    cost: 1,
    value: 1,
    text: "重整士氣，恢復體力並補充手牌。抽 1 張牌並回復 1 點體力。",
  },
  {
    id: "fire-attack-1",
    name: "火攻",
    kind: "fire",
    cost: 1,
    value: 1,
    text: "趁敵蓄勢未發，以火攻破其陣腳。敵人蓄力時造成 2 點傷害並打斷蓄力，否則造成 1 點傷害。",
  },
  {
    id: "fire-attack-2",
    name: "火攻",
    kind: "fire",
    cost: 1,
    value: 1,
    text: "趁敵蓄勢未發，以火攻破其陣腳。敵人蓄力時造成 2 點傷害並打斷蓄力，否則造成 1 點傷害。",
  },
];

export const starterDeck: Card[] = baseStarterDeck.map((card) => ({
  ...card,
  ...cardVisuals[card.name],
}));
