import type { Card } from "./types";

export const equipmentEffects = {
  greenDragonBlade: "每回合第一次斬額外 +1 傷害",
  diluHorse: "每場戰鬥第一次受到攻擊時自動閃避",
  taipingManual: "每回合第一次兵書額外抽 1 張",
} as const;

export const starterDeck: Card[] = [
  {
    id: "slash-1",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-1",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "wine-1",
    name: "酒",
    kind: "wine",
    cost: 0,
    value: 1,
    text: "下一張斬傷害 +1，並恢復 1 點體力。",
  },
  {
    id: "manual-1",
    name: "兵書",
    kind: "draw",
    cost: 1,
    value: 2,
    text: "抽 2 張牌。",
  },
  {
    id: "pierce-1",
    name: "破甲",
    kind: "pierce",
    cost: 1,
    value: 1,
    text: "造成 1 點傷害，移除敵人防守，下一次斬傷害 +1。",
  },
  {
    id: "slash-2",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-2",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-3",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "manual-2",
    name: "兵書",
    kind: "draw",
    cost: 1,
    value: 2,
    text: "抽 2 張牌。",
  },
  {
    id: "wine-2",
    name: "酒",
    kind: "wine",
    cost: 0,
    value: 1,
    text: "下一張斬傷害 +1，並恢復 1 點體力。",
  },
  {
    id: "pierce-2",
    name: "破甲",
    kind: "pierce",
    cost: 1,
    value: 1,
    text: "造成 1 點傷害，移除敵人防守，下一次斬傷害 +1。",
  },
  {
    id: "slash-4",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-3",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-5",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "wine-3",
    name: "酒",
    kind: "wine",
    cost: 0,
    value: 1,
    text: "下一張斬傷害 +1，並恢復 1 點體力。",
  },
  {
    id: "dodge-4",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-6",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "dodge-5",
    name: "閃",
    kind: "dodge",
    cost: 0,
    value: 0,
    text: "敵人攻擊時可選擇使用，抵消該次傷害。趙雲可當作斬使用。",
  },
  {
    id: "slash-7",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "slash-8",
    name: "斬",
    kind: "attack",
    cost: 1,
    value: 2,
    text: "造成 2 點傷害。關羽可觸發武聖，趙雲可當作閃使用。",
  },
  {
    id: "green-dragon-blade-1",
    name: "青龍偃月刀",
    kind: "equipment",
    cost: 1,
    value: 0,
    text: `裝備。攻擊流。${equipmentEffects.greenDragonBlade}。`,
  },
  {
    id: "dilu-horse-1",
    name: "的盧馬",
    kind: "equipment",
    cost: 1,
    value: 0,
    text: `裝備。防守流。${equipmentEffects.diluHorse}。`,
  },
  {
    id: "taiping-manual-1",
    name: "太平要術",
    kind: "equipment",
    cost: 1,
    value: 0,
    text: `裝備。策略流。${equipmentEffects.taipingManual}。`,
  },
  {
    id: "combo-slash-1",
    name: "連斬",
    kind: "combo",
    cost: 1,
    value: 1,
    text: "趁敵勢已亂，連續追擊。造成 1 點傷害；若敵人已受傷，抽 1 張牌。",
  },
  {
    id: "combo-slash-2",
    name: "連斬",
    kind: "combo",
    cost: 1,
    value: 1,
    text: "趁敵勢已亂，連續追擊。造成 1 點傷害；若敵人已受傷，抽 1 張牌。",
  },
  {
    id: "guard-1",
    name: "固守",
    kind: "guard",
    cost: 1,
    value: 1,
    text: "穩住陣腳，減少下一次傷害。本回合下一次受到傷害 -1。",
  },
  {
    id: "guard-2",
    name: "固守",
    kind: "guard",
    cost: 1,
    value: 1,
    text: "穩住陣腳，減少下一次傷害。本回合下一次受到傷害 -1。",
  },
  {
    id: "rally-1",
    name: "激勵",
    kind: "rally",
    cost: 1,
    value: 1,
    text: "重整士氣，恢復體力並補充手牌。抽 1 張牌並回復 1 點體力。",
  },
  {
    id: "rally-2",
    name: "激勵",
    kind: "rally",
    cost: 1,
    value: 1,
    text: "重整士氣，恢復體力並補充手牌。抽 1 張牌並回復 1 點體力。",
  },
  {
    id: "fire-attack-1",
    name: "火攻",
    kind: "fire",
    cost: 1,
    value: 1,
    text: "趁敵蓄勢未發，以火攻破其陣腳。敵人蓄力時造成 2 點傷害並打斷蓄力，否則造成 1 點傷害。",
  },
  {
    id: "fire-attack-2",
    name: "火攻",
    kind: "fire",
    cost: 1,
    value: 1,
    text: "趁敵蓄勢未發，以火攻破其陣腳。敵人蓄力時造成 2 點傷害並打斷蓄力，否則造成 1 點傷害。",
  },
];
